import 'package:flutter/material.dart';

import '../../core/api_client.dart';
import 'profile_screen.dart';

/// Registration step 1 — privacy & confidentiality agreement. Responders see
/// real patient data (names, phone numbers, danger signs, live location), so
/// before anything else they must understand and accept their duties.
/// The backend refuses profile registration until this is signed.
class ConsentScreen extends StatefulWidget {
  const ConsentScreen({super.key, required this.user});

  final Map<String, dynamic> user;

  @override
  State<ConsentScreen> createState() => _ConsentScreenState();
}

class _ConsentScreenState extends State<ConsentScreen> {
  bool _confidentiality = false;
  bool _dataProcessing = false;
  bool _busy = false;

  bool get _ready => _confidentiality && _dataProcessing;

  Future<void> _accept() async {
    setState(() => _busy = true);
    try {
      final res = await Api.I.dio.post('/responder/profile', data: {
        'consent': {
          'patientConfidentiality': true,
          'dataProcessing': true,
        },
      });
      final user = res.data['user'] as Map<String, dynamic>;
      if (!mounted) return;
      Navigator.of(context).pushReplacement(
          MaterialPageRoute(builder: (_) => ProfileScreen(user: user)));
    } catch (_) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
            content: Text('Could not save. Check your connection and try again.')));
      }
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: const Text('Privacy & your duties')),
      body: Column(
        children: [
          Expanded(
            child: ListView(
              padding: const EdgeInsets.all(20),
              children: [
                Row(
                  children: [
                    Icon(Icons.shield, color: theme.colorScheme.primary, size: 32),
                    const SizedBox(width: 10),
                    Expanded(
                      child: Text('Patient data is protected.\nRead this before you register.',
                          style: theme.textTheme.titleMedium
                              ?.copyWith(fontWeight: FontWeight.bold)),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                const _Section(
                  icon: Icons.visibility,
                  title: 'What you will see',
                  points: [
                    'Patient names, phone numbers, reported danger signs and location — only for urgent cases routed to you.',
                    'Health risk reports generated by the GrowWithMe app.',
                  ],
                ),
                const _Section(
                  icon: Icons.gavel,
                  title: 'What you MUST do',
                  points: [
                    'Use patient information only to respond to that case.',
                    'Keep everything confidential — like hospital medical records.',
                    'Contact a patient only about their own case.',
                    'Report to the patient\'s facility, not on social media.',
                  ],
                ),
                const _Section(
                  icon: Icons.block,
                  title: 'What you must NEVER do',
                  points: [
                    'Share, screenshot or post patient information anywhere.',
                    'Use a patient\'s phone number or location for anything other than their case.',
                    'Claim a professional tier (nurse, midwife, doctor) you do not hold — false credentials lead to removal and may be reported to the authorities.',
                  ],
                ),
                const _Section(
                  icon: Icons.lock,
                  title: 'How your data is protected',
                  points: [
                    'Your ID documents and live location are encrypted in transit and stored securely; location is used only to route nearby cases to you.',
                    'Handled in line with Ghana\'s Data Protection Act, 2012 (Act 843) and HIPAA-style health-privacy safeguards.',
                    'Access to patient data is logged. Breaking these rules ends your access.',
                  ],
                ),
                const SizedBox(height: 8),
                CheckboxListTile(
                  value: _confidentiality,
                  onChanged: (v) => setState(() => _confidentiality = v ?? false),
                  controlAffinity: ListTileControlAffinity.leading,
                  title: const Text(
                      'I will keep all patient information confidential and use it only to provide care.'),
                ),
                CheckboxListTile(
                  value: _dataProcessing,
                  onChanged: (v) => setState(() => _dataProcessing = v ?? false),
                  controlAffinity: ListTileControlAffinity.leading,
                  title: const Text(
                      'I consent to my ID documents and live location being processed to verify me and route urgent cases.'),
                ),
              ],
            ),
          ),
          SafeArea(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
              child: FilledButton(
                style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16)),
                onPressed: _ready && !_busy ? _accept : null,
                child: _busy
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2))
                    : Text(_ready
                        ? 'I agree — continue'
                        : 'Tick both boxes to continue'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({required this.icon, required this.title, required this.points});

  final IconData icon;
  final String title;
  final List<String> points;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 20, color: theme.colorScheme.primary),
              const SizedBox(width: 8),
              Text(title,
                  style: theme.textTheme.titleSmall
                      ?.copyWith(fontWeight: FontWeight.bold)),
            ],
          ),
          const SizedBox(height: 6),
          for (final p in points)
            Padding(
              padding: const EdgeInsets.only(left: 28, bottom: 4),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('•  '),
                  Expanded(child: Text(p, style: const TextStyle(height: 1.35))),
                ],
              ),
            ),
        ],
      ),
    );
  }
}
